#!/usr/bin/with-contenv bash

function initEnv() 
{
  local LIST_PATH=/scripts/task.list
  local LOGS_PATH=/scripts/logs

  echo "........................................"

  [[ ! -f ${LOGS_PATH} ]] && mkdir ${LOGS_PATH}
  [[ $(cat ${LIST_PATH}) != $(crontab -l) ]] && crontab ${LIST_PATH} 
  echo "task added successfully !"
  
  echo "........................................"
}

initEnv 2>&1 | sed "s#^#[cont-init.d] $(basename $0): \1#g"
